-- ============================================
-- SEPJ Gabès - Seed Data
-- Initial data for first-time setup
-- ============================================

USE `sepj_gabes`;

-- ============================================
-- 1. DEFAULT ADMIN USER
-- Password: Admin12345!
-- Hash generated by: password_hash('Admin12345!', PASSWORD_DEFAULT)
-- You can regenerate with: php database/create_admin_hash.php
-- ============================================
INSERT INTO `users` (`name`, `email`, `password_hash`, `role`, `status`, `created_at`) VALUES
('مدير النظام', 'admin@sepj.local', '$2y$10$XQw794op7aRQVJRX5KovXuAWUKj7WvLBvfcj5ucCCbfbTau540DtW', 'admin', 'active', NOW());

-- Note: The hash above is a placeholder. Run create_admin_hash.php to generate a proper hash.
-- Use: UPDATE users SET password_hash = 'NEW_HASH' WHERE email = 'admin@sepj.local';

-- ============================================
-- 2. SITE SETTINGS
-- ============================================
INSERT INTO `site_settings` (`setting_key`, `value_ar`, `value_fr`, `value_en`, `value_raw`) VALUES

-- Company Info
('company_name', 'شركة البيئة والغراسة والبستنة بقابس', 'Société d\'Environnement, Plantation et Jardinage de Gabès', 'Environment, Plantation and Gardening Company of Gabès', NULL),

('company_short_name', 'SEPJ Gabès', 'SEPJ Gabès', 'SEPJ Gabès', NULL),

('mission_statement', 'شركة رائدة في مجال البيئة والتنمية المستدامة بجهة ڨابس', 'Entreprise leader dans le domaine de l\'environnement et du développement durable dans la région de Gabès', 'Leading company in environment and sustainable development in the Gabès region', NULL),

('about_summary', 'تأسست شركة البيئة والغراسة والبستنة بقابس في 15 أفريل 2011، ونشرت في الرائد الرسمي للجمهورية التونسية في 15 نوفمبر 2011. الشركة تابعة للمجمع الكيميائي التونسي الذي يمتلك حوالي 99% من رأس مال الشركة.', 'La Société d\'Environnement, Plantation et Jardinage de Gabès a été créée le 15 avril 2011 et publiée au Journal Officiel de la République Tunisienne le 15 novembre 2011. La société est affiliée au Groupe Chimique Tunisien qui détient environ 99% du capital de la société.', 'The Environment, Plantation and Gardening Company of Gabès was established on April 15, 2011, and was published in the Official Gazette of the Republic of Tunisia on November 15, 2011. The company is affiliated with the Tunisian Chemical Group which owns approximately 99% of the company\'s capital.', NULL),

('director_name', 'السيد عبد السلام بسيسة', 'M. Abdel Salam Besisse', 'Mr. Abdel Salam Besisse', NULL),

-- Contact Info
('phone', NULL, NULL, NULL, '75 266 037'),
('fax', NULL, NULL, NULL, '75 266 038'),
('email_primary', NULL, NULL, NULL, 'Contact@SEPJGabes.tn'),
('email_secondary', NULL, NULL, NULL, 'Coordinateur@SEPJGabes.tn'),
('po_box', NULL, NULL, NULL, 'ص.ب عدد 206 ڨابس 6000'),
('address', 'المنطقة الصناعية بڨابس', 'Zone Industrielle de Gabès', 'Industrial Zone of Gabès', NULL),

-- Social Media
('facebook_url', NULL, NULL, NULL, 'https://www.facebook.com/SEPJGabes.tn'),

-- Homepage Hero
('hero_title', 'شركة البيئة والغراسة والبستنة بقابس', 'Société d\'Environnement, Plantation et Jardinage de Gabès', 'Environment, Plantation and Gardening Company of Gabès', NULL),

('hero_subtitle', 'شركة رائدة في مجال البيئة والتنمية المستدامة', 'Entreprise leader dans l\'environnement et le développement durable', 'Leading company in environment and sustainable development', NULL),

-- Stats
('stat_founded_label', 'تأسست في', 'Fondée en', 'Founded in', NULL),
('stat_founded_value', NULL, NULL, NULL, '2011'),

('stat_trees_label', 'شجرة مزروعة', 'Arbres plantés', 'Trees planted', NULL),
('stat_trees_value', NULL, NULL, NULL, '400'),

('stat_hectares_label', 'هكتار محولة', 'Hectares transformés', 'Hectares transformed', NULL),
('stat_hectares_value', NULL, NULL, NULL, '10'),

('stat_activation_label', 'نسبة التفعيل', 'Taux d\'activation', 'Activation rate', NULL),
('stat_activation_value', NULL, NULL, NULL, '76%'),

('stat_activation_goal', 'هدف الوصول إلى', 'Objectif d\'atteindre', 'Goal to reach', NULL),
('stat_activation_goal_value', NULL, NULL, NULL, '100%'),
('stat_activation_year', NULL, NULL, NULL, '2025'),

-- SEO
('seo_title', 'SEPJ Gabès - شركة البيئة والغراسة والبستنة بقابس', 'SEPJ Gabès - Société d\'Environnement, Plantation et Jardinage de Gabès', 'SEPJ Gabès - Environment, Plantation and Gardening Company of Gabès', NULL),

('seo_description', 'الموقع الرسمي لشركة البيئة والغراسة والبستنة بقابس - التابعة للمجمع الكيميائي التونسي', 'Site officiel de la Société d\'Environnement, Plantation et Jardinage de Gabès - affiliée au Groupe Chimique Tunisien', 'Official website of the Environment, Plantation and Gardening Company of Gabès - affiliated with the Tunisian Chemical Group', NULL),

-- Footer
('footer_text', 'جميع الحقوق محفوظة لشركة البيئة والغراسة والبستنة بقابس', 'Tous droits réservés à la Société d\'Environnement, Plantation et Jardinage de Gabès', 'All rights reserved to the Environment, Plantation and Gardening Company of Gabès', NULL);

-- ============================================
-- 3. NAVIGATION ITEMS
-- ============================================
INSERT INTO `navigation_items` (`label_ar`, `label_fr`, `label_en`, `url`, `parent_id`, `sort_order`, `is_active`) VALUES
('استقبال', 'Accueil', 'Home', 'index.php', NULL, 1, 1),
('تقديم الشركة', 'À propos', 'About us', 'page.php?slug=about-company', NULL, 2, 1),
('كلمة المدير العام', 'Mot du DG', 'Director\'s Message', 'page.php?slug=director-message', NULL, 3, 1),
('مشاريعنا', 'Nos Projets', 'Our Projects', 'projects.php', NULL, 4, 1),
('خدماتنا', 'Nos Services', 'Our Services', 'services.php', NULL, 5, 1),
('المسؤولية المجتمعية', 'RSE', 'CSR', 'rse.php', NULL, 6, 1),
('الموارد والتنمية', 'Ressources', 'Resources', 'resources.php', NULL, 7, 1),
('الرياضة والعمل', 'Sports', 'Sports & Work', 'sports.php', NULL, 8, 1),
('أخبار', 'Actualités', 'News', 'news.php', NULL, 9, 1),
('أنشطة', 'Activités', 'Activities', 'activities.php', NULL, 10, 1),
('تتويجات', 'Distinctions', 'Awards', 'prizes.php', NULL, 11, 1),
('معرض الصور', 'Galerie Photos', 'Gallery', 'gallery.php', NULL, 12, 1),
('معرض الفيديو', 'Galerie Vidéo', 'Videos', 'videos.php', NULL, 13, 1),
('الاتصال بنا', 'Nous Contacter', 'Contact Us', 'contact.php', NULL, 14, 1);

-- RSE Sub-items
INSERT INTO `navigation_items` (`label_ar`, `label_fr`, `label_en`, `url`, `parent_id`, `sort_order`, `is_active`) VALUES
('التزام مجتمعي', 'Engagement Social', 'Social Commitment', 'rse.php?type=social', 6, 1, 1),
('المساهمة البيئية', 'Contribution Environnementale', 'Environmental Contribution', 'rse.php?type=environmental', 6, 2, 1);

-- ============================================
-- 4. SEED CONTENT
-- ============================================

-- 4a. About Company Page
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('page', 'about-company',
 'تقديم الشركة',
 'À propos de la société',
 'About the Company',
 'شركة البيئة والغراسة والبستنة بقابس شركة تابعة للمجمع الكيميائي التونسي، تأسست في 15 أفريل 2011.',
 'Société d\'Environnement, Plantation et Jardinage de Gabès, filiale du Groupe Chimique Tunisien, créée le 15 avril 2011.',
 'Environment, Plantation and Gardening Company of Gabès, a subsidiary of the Tunisian Chemical Group, established on April 15, 2011.',
 '<h2>تقديم الشركة</h2><p>شركة البيئة والغراسة والبستنة بقابس هي شركة تابعة للمجمع الكيميائي التونسي. تأسست الشركة في 15 أفريل 2011 وتم نشرها في الرائد الرسمي للجمهورية التونسية في 15 نوفمبر 2011.</p><p>يمتلك المجمع الكيميائي التونسي حوالي 99% من رأس مال الشركة.</p><h3>مجالات النشاط</h3><ul><li>البيئة والتنمية المستدامة</li><li>الغراسة والبستنة</li><li>المساهمة في التنمية المحلية</li><li>التشغيل والتدريب</li></ul>',
 '<h2>Présentation de la société</h2><p>La Société d\'Environnement, Plantation et Jardinage de Gabès est une filiale du Groupe Chimique Tunisien. La société a été créée le 15 avril 2011 et publiée au Journal Officiel de la République Tunisienne le 15 novembre 2011.</p><p>Le Groupe Chimique Tunisien détient environ 99% du capital de la société.</p><h3>Domaines d\'activité</h3><ul><li>Environnement et développement durable</li><li>Plantation et jardinage</li><li>Contribution au développement local</li><li>Emploi et formation</li></ul>',
 '<h2>About the Company</h2><p>The Environment, Plantation and Gardening Company of Gabès is a subsidiary of the Tunisian Chemical Group. The company was established on April 15, 2011 and was published in the Official Gazette of the Republic of Tunisia on November 15, 2011.</p><p>The Tunisian Chemical Group owns approximately 99% of the company\'s capital.</p><h3>Areas of Activity</h3><ul><li>Environment and sustainable development</li><li>Plantation and gardening</li><li>Contribution to local development</li><li>Employment and training</li></ul>',
 'published', 1, NOW(), NOW());

-- 4b. Director Message Page
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('page', 'director-message',
 'كلمة السيد المدير العام',
 'Mot du Directeur Général',
 'Director\'s Message',
 'كلمة السيد عبد السلام بسيسة، المدير العام لشركة البيئة والغراسة والبستنة بقابس.',
 'Mot de M. Abdel Salam Besisse, Directeur Général de la Société d\'Environnement, Plantation et Jardinage de Gabès.',
 'Message from Mr. Abdel Salam Besisse, General Director of the Environment, Plantation and Gardening Company of Gabès.',
 '<h2>كلمة السيد المدير العام</h2><p>بسم الله الرحمن الرحيم</p><p>السيدات والسادة،</p><p>يسعدني أن أرحب بكم في الموقع الرسمي لشركة البيئة والغراسة والبستنة بقابس.</p><p>إن شركتنا، التابعة للمجمع الكيميائي التونسي، تعمل منذ تأسيسها في 15 أفريل 2011 على تحقيق أهدافها في مجال البيئة والتنمية المستدامة بجهة ڨابس.</p><p>نعمل جاهدين للوصول إلى نسبة تفعيل 100% في أقرب الآجال، وقد بلغت نسبة التفعيل 76% في نهاية سنة 2025.</p><p>نشكر جميع عملائنا وشركائنا على ثقتهم، ونتطلع إلى مزيد من التعاون المثمر.</p><p>والسلام عليكم ورحمة الله وبركاته</p><p><strong>عبد السلام بسيسة</strong><br>المدير العام</p>',
 '<h2>Mot du Directeur Général</h2><p>Mesdames, Messieurs,</p><p>J\'ai le plaisir de vous souhaiter la bienvenue sur le site officiel de la Société d\'Environnement, Plantation et Jardinage de Gabès.</p><p>Notre société, filiale du Groupe Chimique Tunisien, œuvre depuis sa création le 15 avril 2011 pour atteindre ses objectifs dans le domaine de l\'environnement et du développement durable dans la région de Gabès.</p><p>Nous travaillons d\'arrache-pied pour atteindre un taux d\'activation de 100% dans les plus brefs délais, et nous avons atteint 76% à la fin de l\'année 2025.</p><p>Nous remercions tous nos clients et partenaires pour leur confiance, et nous nous réjouissons d\'une collaboration plus fructueuse.</p><p><strong>Abdel Salam Besisse</strong><br>Directeur Général</p>',
 '<h2>Director\'s Message</h2><p>Ladies and Gentlemen,</p><p>It is my pleasure to welcome you to the official website of the Environment, Plantation and Gardening Company of Gabès.</p><p>Our company, a subsidiary of the Tunisian Chemical Group, has been working since its establishment on April 15, 2011 to achieve its goals in the field of environment and sustainable development in the Gabès region.</p><p>We are working hard to reach an activation rate of 100% as soon as possible, having reached 76% at the end of 2025.</p><p>We thank all our customers and partners for their trust, and we look forward to more fruitful collaboration.</p><p><strong>Abdel Salam Besisse</strong><br>General Director</p>',
 'published', 1, NOW(), NOW());

-- 4c. Board Meeting News - May 2026
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('post', 'board-meeting-may-2026',
 'اجتماع مجلس الإدارة - ماي 2026',
 'Conseil d\'administration - Mai 2026',
 'Board Meeting - May 2026',
 'اجتماع مجلس الإدارة يوم 25 ماي 2026 لمناقشة القوائم المالية لسنة 2025 والاستراتيجية المستقبلية للشركة.',
 'Réunion du conseil d\'administration le 25 mai 2026 pour discuter des états financiers 2025 et de la stratégie future de la société.',
 'Board of Directors meeting on May 25, 2026 to discuss the 2025 financial statements and the company\'s future strategy.',
 '<h2>اجتماع مجلس الإدارة</h2><p>عقد مجلس إدارة شركة البيئة والغراسة والبستنة بقابس اجتماعه الدوري يوم 25 ماي 2026.</p><h3>النقاط الرئيسية</h3><ul><li>مناقشة القوائم المالية لسنة 2025</li><li>عرض الإستراتيجية المستقبلية للشركة</li><li>بلغت نسبة التفعيل 76% في نهاية سنة 2025</li><li>الهدف هو الوصول إلى نسبة تفعيل 100%</li></ul><p>أشرف على الاجتماع السيد عبد السلام بسيسة المدير العام للشركة، بحضور أعضاء مجلس الإدارة.</p>',
 '<h2>Réunion du Conseil d\'administration</h2><p>Le Conseil d\'administration de la Société d\'Environnement, Plantation et Jardinage de Gabès a tenu sa réunion périodique le 25 mai 2026.</p><h3>Points principaux</h3><ul><li>Discussion des états financiers 2025</li><li>Présentation de la stratégie future de la société</li><li>Le taux d\'activation a atteint 76% à la fin de 2025</li><li>L\'objectif est d\'atteindre un taux d\'activation de 100%</li></ul><p>La réunion était présidée par M. Abdel Salam Besisse, Directeur Général de la société, en présence des membres du Conseil d\'administration.</p>',
 '<h2>Board of Directors Meeting</h2><p>The Board of Directors of the Environment, Plantation and Gardening Company of Gabès held its periodic meeting on May 25, 2026.</p><h3>Key Points</h3><ul><li>Discussion of the 2025 financial statements</li><li>Presentation of the company\'s future strategy</li><li>Activation rate reached 76% at the end of 2025</li><li>Goal is to reach 100% activation rate</li></ul><p>The meeting was chaired by Mr. Abdel Salam Besisse, General Director of the company, in the presence of Board members.</p>',
 'published', 1, '2026-05-25 10:00:00', NOW());

-- 4d. Olive Oil Initiative
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('post', 'olive-oil-initiative',
 'مبادرة بيع الزيتون مباشرة من مشروع منزل الحبيب',
 'Initiative de vente directe d\'huile d\'olive du projet Manzel El Habib',
 'Direct Olive Oil Sale Initiative from Manzel El Habib Project',
 'مبادرة لبيع زيت الزيتون مباشرة من مشروع منزل الحبيب بأسعار تنافسية.',
 'Initiative de vente directe d\'huile d\'olive à partir du projet Manzel El Habib à des prix compétitifs.',
 'Initiative to sell olive oil directly from the Manzel El Habib project at competitive prices.',
 '<h2>مبادرة بيع الزيتون مباشرة</h2><p>في إطار تعزيز التنمية المحلية، أطلقت شركة البيئة والغراسة والبستنة بقابس مبادرة لبيع زيت الزيتون مباشرة من مشروع منزل الحبيب.</p><p>تهدف هذه المبادرة إلى توفير زيت زيتون بجودة عالية وبأسعار تنافسية للمستهلكين.</p><p>للمزيد من المعلومات، يرجى الاتصال بإدارة الشركة.</p>',
 '<h2>Initiative de vente directe d\'huile d\'olive</h2><p>Dans le cadre de la promotion du développement local, la Société d\'Environnement, Plantation et Jardinage de Gabès a lancé une initiative de vente directe d\'huile d\'olive à partir du projet Manzel El Habib.</p><p>Cette initiative vise à fournir une huile d\'olive de haute qualité à des prix compétitifs aux consommateurs.</p><p>Pour plus d\'informations, veuillez contacter la direction de la société.</p>',
 '<h2>Direct Olive Oil Sale Initiative</h2><p>As part of promoting local development, the Environment, Plantation and Gardening Company of Gabès launched an initiative to sell olive oil directly from the Manzel El Habib project.</p><p>This initiative aims to provide high-quality olive oil at competitive prices to consumers.</p><p>For more information, please contact the company management.</p>',
 'published', 0, '2026-04-15 09:00:00', NOW());

-- 4e. Chenchou Sustainable Agriculture
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('project', 'chenchou-sustainable-agriculture',
 'شراكة الشنشو/OEP للفلاحة المستدامة',
 'Partenariat Chenchou/OEP pour l\'agriculture durable',
 'Chenchou/OEP Sustainable Agriculture Partnership',
 '10 هكتارات من المحاصيل العلفية في 2025 والتوسع بـ 5 هكتارات إضافية في 2026.',
 '10 hectares de cultures fourragères en 2025 et expansion de 5 hectares supplémentaires en 2026.',
 '10 hectares of forage crops in 2025 and expansion by 5 additional hectares in 2026.',
 '<h2>شراكة الشنشو/OEP للفلاحة المستدامة</h2><p>في إطار التعاون مع المعهد الوطني للزراعة (OEP)، أطلقت شركة البيئة والغراسة والبستنة بقابس مشروعا للفلاحة المستدامة في منطقة الشنشو.</p><h3>تفاصيل المشروع</h3><ul><li>10 هكتارات من المحاصيل العلفية في سنة 2025</li><li>التوسع بـ 5 هكتارات إضافية في سنة 2026</li><li>استعمال تقنيات الري الحديثة</li><li>تحسين جودة المحاصيل</li></ul>',
 '<h2>Partenariat Chenchou/OEP pour l\'agriculture durable</h2><p>Dans le cadre de la coopération avec l\'Office de l\'Élevage et des Pâturages (OEP), la Société d\'Environnement, Plantation et Jardinage de Gabès a lancé un projet d\'agriculture durable dans la région de Chenchou.</p><h3>Détails du projet</h3><ul><li>10 hectares de cultures fourragères en 2025</li><li>Expansion de 5 hectares supplémentaires en 2026</li><li>Utilisation de techniques d\'irrigation modernes</li><li>Amélioration de la qualité des cultures</li></ul>',
 '<h2>Chenchou/OEP Sustainable Agriculture Partnership</h2><p>As part of cooperation with the Livestock and Pastures Office (OEP), the Environment, Plantation and Gardening Company of Gabès launched a sustainable agriculture project in the Chenchou region.</p><h3>Project Details</h3><ul><li>10 hectares of forage crops in 2025</li><li>Expansion by 5 additional hectares in 2026</li><li>Use of modern irrigation techniques</li><li>Improvement of crop quality</li></ul>',
 'published', 1, '2025-12-01 10:00:00', NOW());

-- 4f. Green Belt Planting
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('activity', 'green-belt-planting',
 'غرس الحزام الأخضر: 400 شجرة Ficus vert',
 'Plantation de la ceinture verte : 400 Ficus vert',
 'Green Belt Planting: 400 Ficus vert Trees',
 'تم غرس 400 شجرة من نوع Ficus vert في إطار مشروع الحزام الأخضر بتاريخ 20 جانفي 2026.',
 'Plantation de 400 arbres Ficus vert dans le cadre du projet de ceinture verte le 20 janvier 2026.',
 '400 Ficus vert trees were planted as part of the green belt project on January 20, 2026.',
 '<h2>غرس الحزام الأخضر</h2><p>في إطار المشاريع البيئية للشركة، تم غرس 400 شجرة من نوع Ficus vert في 20 جانفي 2026.</p><p>هذه المبادرة تهدف إلى تعزيز الغطاء النباتي في المنطقة والمساهمة في تحسين جودة الهواء والبيئة.</p>',
 '<h2>Plantation de la ceinture verte</h2><p>Dans le cadre des projets environnementaux de la société, 400 arbres Ficus vert ont été plantés le 20 janvier 2026.</p><p>Cette initiative vise à renforcer la couverture végétale dans la région et à contribuer à l\'amélioration de la qualité de l\'air et de l\'environnement.</p>',
 '<h2>Green Belt Planting</h2><p>As part of the company\'s environmental projects, 400 Ficus vert trees were planted on January 20, 2026.</p><p>This initiative aims to strengthen vegetation cover in the region and contribute to improving air quality and the environment.</p>',
 'published', 1, '2026-01-20 14:00:00', NOW());

-- 4g. Bouchemma Cleaning Intervention
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('activity', 'bouchemma-cleaning',
 'تدخل تنظيف بوشمة',
 'Intervention de nettoyage à Bouchemma',
 'Cleaning Intervention in Bouchemma',
 'تدخل تنظيف في منطقة بوشمة بتاريخ 9 جانفي 2026.',
 'Intervention de nettoyage dans la région de Bouchemma le 9 janvier 2026.',
 'Cleaning intervention in the Bouchemma area on January 9, 2026.',
 '<h2>تدخل تنظيف بوشمة</h2><p>في إطار المسؤولية المجتمعية للشركة، قامت شركة البيئة والغراسة والبستنة بقابس بتدخل نظافة في منطقة بوشمة بتاريخ 9 جانفي 2026.</p><p>شمل التدخل تنظيف الأماكن العامة والطرقات، بمشاركة أعوان الشركة.</p>',
 '<h2>Intervention de nettoyage à Bouchemma</h2><p>Dans le cadre de la responsabilité sociétale de la société, la Société d\'Environnement, Plantation et Jardinage de Gabès a effectué une intervention de nettoyage dans la région de Bouchemma le 9 janvier 2026.</p><p>L\'intervention a inclus le nettoyage des lieux publics et des routes, avec la participation des agents de la société.</p>',
 '<h2>Cleaning Intervention in Bouchemma</h2><p>As part of the company\'s social responsibility, the Environment, Plantation and Gardening Company of Gabès carried out a cleaning intervention in the Bouchemma area on January 9, 2026.</p><p>The intervention included cleaning public places and roads, with the participation of company agents.</p>',
 'published', 0, '2026-01-09 08:00:00', NOW());

-- 4h. JCC Ghannouch Event
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('activity', 'jcc-ghannouch-preparation',
 'التحضير لتظاهرة JCC/غانوش',
 'Préparation de l\'événement JCC/Ghannouch',
 'Preparation for JCC/Ghannouch Event',
 'التحضير لتظاهرة JCC/غانوش بتاريخ 25 ديسمبر 2025.',
 'Préparation de l\'événement JCC/Ghannouch le 25 décembre 2025.',
 'Preparation for the JCC/Ghannouch event on December 25, 2025.',
 '<h2>التحضير لتظاهرة JCC/غانوش</h2><p>قامت شركة البيئة والغراسة والبستنة بقابس بالتحضير للتظاهرة الثقافية JCC/غانوش بتاريخ 25 ديسمبر 2025.</p><p>شملت الاستعدادات تنظيف وتجميل الفضاءات الخاصة بالتظاهرة.</p>',
 '<h2>Préparation de l\'événement JCC/Ghannouch</h2><p>La Société d\'Environnement, Plantation et Jardinage de Gabès a préparé l\'événement culturel JCC/Ghannouch le 25 décembre 2025.</p><p>Les préparatifs comprenaient le nettoyage et l\'embellissement des espaces de l\'événement.</p>',
 '<h2>Preparation for JCC/Ghannouch Event</h2><p>The Environment, Plantation and Gardening Company of Gabès prepared for the JCC/Ghannouch cultural event on December 25, 2025.</p><p>The preparations included cleaning and beautifying the event spaces.</p>',
 'published', 0, '2025-12-25 09:00:00', NOW());

-- 4i. Saniet El Bey Youth Complex
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('activity', 'saniet-el-bey-intervention',
 'تدخل بالمركب الشبابي سانية الباي',
 'Intervention au complexe des jeunes Saniet El Bey',
 'Intervention at Saniet El Bey Youth Complex',
 'تدخل في الفضاءات الخارجية للمركب الشبابي سانية الباي بتاريخ 21 ديسمبر 2025.',
 'Intervention dans les espaces extérieurs du complexe des jeunes Saniet El Bey le 21 décembre 2025.',
 'Intervention in the external spaces of the Saniet El Bey youth complex on December 21, 2025.',
 '<h2>تدخل بالمركب الشبابي سانية الباي</h2><p>في إطار دعم المرافق الشبابية، قامت الشركة بالتدخل في الفضاءات الخارجية للمركب الشبابي سانية الباي بتاريخ 21 ديسمبر 2025.</p><p>شمل التدخل صيانة وتجميل المساحات الخضراء بالمركب.</p>',
 '<h2>Intervention au complexe des jeunes Saniet El Bey</h2><p>Dans le cadre du soutien aux installations pour jeunes, la société est intervenue dans les espaces extérieurs du complexe des jeunes Saniet El Bey le 21 décembre 2025.</p><p>L\'intervention comprenait l\'entretien et l\'embellissement des espaces verts du complexe.</p>',
 '<h2>Intervention at Saniet El Bey Youth Complex</h2><p>As part of supporting youth facilities, the company intervened in the external spaces of the Saniet El Bey youth complex on December 21, 2025.</p><p>The intervention included maintenance and beautification of the complex\'s green spaces.</p>',
 'published', 0, '2025-12-21 10:00:00', NOW());

-- 4j. Sports and Work Page
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('sport', 'sports-and-work',
 'الرياضة والعمل',
 'Sports et Travail',
 'Sports & Work',
 'الأنشطة الرياضية للشركة: فرق كرة القدم +40 و-40، الكرة الطائرة للنساء، البيتانك للرجال.',
 'Activités sportives de la société : équipes de football +40 et -40, volley-ball féminin, pétanque masculine.',
 'Company sports activities: football teams +40 and -40, women\'s volleyball, men\'s pétanque.',
 '<h2>الرياضة والعمل</h2><p>تولي شركة البيئة والغراسة والبستنة بقابس أهمية كبيرة للأنشطة الرياضية كجزء من ثقافة المؤسسة.</p><h3>الفرق الرياضية</h3><ul><li>فريق كرة القدم +40</li><li>فريق كرة القدم -40</li><li>فريق الكرة الطائرة للنساء</li><li>فريق البيتانك للرجال</li></ul><h3>الإنجازات</h3><p>تحصلت الفرق الرياضية للشركة على عدة تتويجات في البطولات المحلية والجهوية، مما يعكس الروح الرياضية العالية لدى أعوان الشركة.</p>',
 '<h2>Sports et Travail</h2><p>La Société d\'Environnement, Plantation et Jardinage de Gabès accorde une grande importance aux activités sportives dans le cadre de sa culture d\'entreprise.</p><h3>Équipes sportives</h3><ul><li>Équipe de football +40</li><li>Équipe de football -40</li><li>Équipe de volley-ball féminin</li><li>Équipe de pétanque masculine</li></ul><h3>Réalisations</h3><p>Les équipes sportives de la société ont remporté plusieurs distinctions dans les championnats locaux et régionaux, reflétant l\'esprit sportif élevé des agents de la société.</p>',
 '<h2>Sports & Work</h2><p>The Environment, Plantation and Gardening Company of Gabès places great importance on sports activities as part of its corporate culture.</p><h3>Sports Teams</h3><ul><li>Football team +40</li><li>Football team -40</li><li>Women\'s volleyball team</li><li>Men\'s pétanque team</li></ul><h3>Achievements</h3><p>The company\'s sports teams have won several awards in local and regional championships, reflecting the high sportsmanship of the company\'s employees.</p>',
 'published', 1, NOW(), NOW());

-- 4k. Resources and Development Page
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('resource', 'resources-and-development',
 'الموارد والتنمية',
 'Ressources et Développement',
 'Resources & Development',
 'الدراسات والتكوين والتدريب والري الذكي وإنترنت الأشياء والموارد البشرية والمحاسبة والمالية والإعلامية.',
 'Études, formation, stages, irrigation intelligente, IoT, RH, finances, comptabilité, informatique.',
 'Studies, training, internships, smart irrigation, IoT, HR, finance, accounting, IT.',
 '<h2>الموارد والتنمية</h2><p>تعمل شركة البيئة والغراسة والبستنة بقابس على تطوير مواردها البشرية والتقنية لتحقيق أفضل النتائج.</p><h3>مجالات التطوير</h3><ul><li>الدراسات والأبحاث في مجال البيئة</li><li>التكوين والتدريب المستمر للأعوان</li><li>برامج التدريب والتطوير المهني</li><li>الري الذكي باستخدام تقنيات حديثة</li><li>إنترنت الأشياء (IoT) في الزراعة</li><li>صندوق الحماية الذكي</li><li>الحاجز الأوتوماتيكي</li></ul><h3>الإدارات</h3><ul><li>الموارد البشرية</li><li>المسؤولية المجتمعية (RSE)</li><li>المالية والمحاسبة</li><li>الإعلامية</li><li>الهندسة الفلاحية</li><li>السلامة الصناعية</li></ul>',
 '<h2>Ressources et Développement</h2><p>La Société d\'Environnement, Plantation et Jardinage de Gabès œuvre pour développer ses ressources humaines et techniques afin d\'obtenir les meilleurs résultats.</p><h3>Domaines de développement</h3><ul><li>Études et recherches environnementales</li><li>Formation continue des agents</li><li>Programmes de stages et développement professionnel</li><li>Irrigation intelligente utilisant des technologies modernes</li><li>Internet des objets (IoT) en agriculture</li><li>Boîtier de garde intelligent</li><li>Barrière automatique</li></ul><h3>Services</h3><ul><li>Ressources humaines</li><li>Responsabilité Sociétale d\'Entreprise (RSE)</li><li>Finances et comptabilité</li><li>Informatique</li><li>Génie agricole</li><li>Sécurité industrielle</li></ul>',
 '<h2>Resources & Development</h2><p>The Environment, Plantation and Gardening Company of Gabès works to develop its human and technical resources to achieve the best results.</p><h3>Development Areas</h3><ul><li>Studies and research in the environmental field</li><li>Continuous training for employees</li><li>Internship and professional development programs</li><li>Smart irrigation using modern technologies</li><li>Internet of Things (IoT) in agriculture</li><li>Smart guard box</li><li>Automatic barrier</li></ul><h3>Departments</h3><ul><li>Human Resources</li><li>Corporate Social Responsibility (CSR)</li><li>Finance and Accounting</li><li>Information Technology</li><li>Agricultural Engineering</li><li>Industrial Safety</li></ul>',
 'published', 1, NOW(), NOW());

-- 4l. Services (sample services)
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('service', 'environmental-cleaning',
 'تنظيف بيئي',
 'Nettoyage environnemental',
 'Environmental Cleaning',
 'خدمات التنظيف البيئي للمساحات العامة والخاصة.',
 'Services de nettoyage environnemental pour les espaces publics et privés.',
 'Environmental cleaning services for public and private spaces.',
 '<h2>خدمات التنظيف البيئي</h2><p>نقدم خدمات التنظيف البيئي باستخدام أحدث المعدات والتقنيات الصديقة للبيئة.</p>',
 '<h2>Services de nettoyage environnemental</h2><p>Nous offrons des services de nettoyage environnemental utilisant les équipements et techniques les plus récents et respectueux de l\'environnement.</p>',
 '<h2>Environmental Cleaning Services</h2><p>We offer environmental cleaning services using the latest eco-friendly equipment and techniques.</p>',
 'published', 0, NOW(), NOW());

INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('service', 'green-space-maintenance',
 'صيانة المساحات الخضراء',
 'Entretien des espaces verts',
 'Green Space Maintenance',
 'خدمات صيانة وتجميل المساحات الخضراء والحدائق.',
 'Services d\'entretien et d\'embellissement des espaces verts et jardins.',
 'Maintenance and beautification services for green spaces and gardens.',
 '<h2>صيانة المساحات الخضراء</h2><p>نقدم خدمات متكاملة لصيانة وتجميل المساحات الخضراء والحدائق العامة والخاصة.</p>',
 '<h2>Entretien des espaces verts</h2><p>Nous offrons des services complets d\'entretien et d\'embellissement des espaces verts et des jardins publics et privés.</p>',
 '<h2>Green Space Maintenance</h2><p>We offer comprehensive maintenance and beautification services for public and private green spaces and gardens.</p>',
 'published', 0, NOW(), NOW());

INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('service', 'tree-plantation',
 'غرس الأشجار',
 'Plantation d\'arbres',
 'Tree Plantation',
 'خدمات غرس الأشجار والنباتات في مختلف المناطق.',
 'Services de plantation d\'arbres et de plantes dans diverses régions.',
 'Tree and plant plantation services in various regions.',
 '<h2>خدمات غرس الأشجار</h2><p>نقدم خدمات غرس الأشجار والنباتات باستخدام أفضل الممارسات لضمان نجاح الغراسة.</p>',
 '<h2>Services de plantation d\'arbres</h2><p>Nous offrons des services de plantation d\'arbres et de plantes utilisant les meilleures pratiques pour garantir le succès de la plantation.</p>',
 '<h2>Tree Plantation Services</h2><p>We offer tree and plant plantation services using best practices to ensure planting success.</p>',
 'published', 0, NOW(), NOW());

-- Prize sample
INSERT INTO `content_items` (`type`, `slug`, `title_ar`, `title_fr`, `title_en`, `summary_ar`, `summary_fr`, `summary_en`, `body_ar`, `body_fr`, `body_en`, `status`, `is_featured`, `published_at`, `created_at`) VALUES
('prize', 'sports-championship-2025',
 'بطولة الرياضة والعمل 2025',
 'Championnat Sports et Travail 2025',
 'Sports & Work Championship 2025',
 'تحصل فريق كرة القدم -40 على المرتبة الأولى في بطولة الرياضة والعمل 2025.',
 'L\'équipe de football -40 a remporté la première place au championnat Sports et Travail 2025.',
 'The football team -40 won first place in the Sports & Work Championship 2025.',
 '<h2>بطولة الرياضة والعمل 2025</h2><p>فاز فريق كرة القدم -40 لشركة البيئة والغراسة والبستنة بقابس بالمرتبة الأولى في بطولة الرياضة والعمل 2025.</p><p>هذا الإنجاز يعكس الروح الرياضية العالية والالتزام لدى أعوان الشركة.</p>',
 '<h2>Championnat Sports et Travail 2025</h2><p>L\'équipe de football -40 de la Société d\'Environnement, Plantation et Jardinage de Gabès a remporté la première place au championnat Sports et Travail 2025.</p><p>Cette réalisation reflète l\'esprit sportif élevé et l\'engagement des agents de la société.</p>',
 '<h2>Sports & Work Championship 2025</h2><p>The football team -40 of the Environment, Plantation and Gardening Company of Gabès won first place in the Sports & Work Championship 2025.</p><p>This achievement reflects the high sportsmanship and commitment of the company\'s employees.</p>',
 'published', 1, NOW(), NOW());